// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP101', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP101', async function() {
    // Test name: CP101
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://tucan.toolsincloud.net/")
    // 2 | setWindowSize | 1197x728 | 
    await driver.manage().window().setRect({ width: 1197, height: 728 })
    // 3 | click | id=auto | 
    await driver.findElement(By.id("auto")).click()
    // 4 | click | id=exampleInputEmail1 | 
    await driver.findElement(By.id("exampleInputEmail1")).click()
    // 5 | type | id=exampleInputEmail1 | 001usuario
    await driver.findElement(By.id("exampleInputEmail1")).sendKeys("001usuariosw")
    // 6 | click | name=username | 
    await driver.findElement(By.name("username")).click()
    // 7 | type | name=username | 001user
    await driver.findElement(By.name("username")).sendKeys("001usernsw")
    // 8 | click | css=.form-group:nth-child(4) > #exampleInputEmail1 | 
    await driver.findElement(By.css(".form-group:nth-child(4) > #exampleInputEmail1")).click()
    // 9 | type | css=.form-group:nth-child(4) > #exampleInputEmail1 | 1user@fake.com
    await driver.findElement(By.css(".form-group:nth-child(4) > #exampleInputEmail1")).sendKeys("101usermail@fake.com")
    // 10 | type | id=exampleInputPassword1 | 00000
    await driver.findElement(By.id("exampleInputPassword1")).sendKeys("00000")
    // 11 | click | name=signup | 
    await driver.findElement(By.name("signup")).click()
    // 13 | click | css=.grid-sidebar:nth-child(9) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(9) img")).click()
    // 14 | click | id=exampleInputEmail1 | 
    await driver.findElement(By.id("exampleInputEmail1")).click()
    await driver.close()
  })
})
