// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP301', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP301', async function() {
    // Test name: CP301
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://tucan.toolsincloud.net/")
    // 2 | setWindowSize | 1197x728 | 
    await driver.manage().window().setRect({ width: 1197, height: 728 })
    // 3 | click | name=email | 
    await driver.findElement(By.name("email")).click()
    // 4 | type | name=email | software@prueba.com
    await driver.findElement(By.name("email")).sendKeys("software@prueba.com")
    // 5 | click | name=password | 
    await driver.findElement(By.name("password")).click()
    // 6 | type | name=password | 123**
    await driver.findElement(By.name("password")).sendKeys("123**")
    // 7 | sendKeys | name=password | ${KEY_ENTER}
    await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
    // 8 | click | css=.grid-sidebar:nth-child(7) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(7) img")).click()
    // 9 | click | css=.home-edit-button | 
    await driver.findElement(By.css(".home-edit-button")).click()
    // 10 | click | css=.image-upload:nth-child(2) .far | 
    await driver.findElement(By.css(".image-upload:nth-child(2) .far")).click()
    // 11 | type | id=file-input | C:\fakepath\div.png
    await driver.findElement(By.id("file-input")).sendKeys("C:\\fakepath\\div.png")
    // 12 | click | name=update | 
    await driver.findElement(By.name("update")).click()
    // 13 | click | css=.home-img-user:nth-child(1) | 
    await driver.findElement(By.css(".home-img-user:nth-child(1)")).click()
    // 14 | close |  | 
    await driver.close()
  })
})
