// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP302', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP302', async function() {
    // Test name: CP302
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1197x728 | 
    await driver.manage().window().setRect({ width: 1197, height: 728 })
    // 3 | click | css=.grid-sidebar:nth-child(9) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(9) img")).click()
    // 4 | click | css=.grid-sidebar:nth-child(7) img | 
    await driver.findElement(By.css(".grid-sidebar:nth-child(7) img")).click()
    // 5 | click | css=.home-edit-button | 
    await driver.findElement(By.css(".home-edit-button")).click()
    // 6 | click | css=.modal-backdrop | 
    await driver.findElement(By.css(".modal-backdrop")).click()
    // 7 | doubleClick | css=.modal-backdrop | 
    {
      const element = await driver.findElement(By.css(".modal-backdrop"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 8 | click | css=.image-upload:nth-child(2) .far | 
    await driver.findElement(By.css(".image-upload:nth-child(2) .far")).click()
    // 9 | type | id=file-input | C:\fakepath\exams.csv
    await driver.findElement(By.id("file-input")).sendKeys("C:\\fakepath\\exams.csv")
    // 10 | click | name=update | 
    await driver.findElement(By.name("update")).click()
    // 11 | click | css=.text-center:nth-child(1) | 
    await driver.findElement(By.css(".text-center:nth-child(1)")).click()
    // 12 | close |  | 
    await driver.close()
  })
})
