// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP401', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP401', async function() {
    // Test name: CP401
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1197x728 | 
    await driver.manage().window().setRect({ width: 1197, height: 728 })
    // 3 | click | css=.form-control | 
    await driver.findElement(By.css(".form-control")).click()
    // 4 | type | css=.form-control | natalia
    await driver.findElement(By.css(".form-control")).sendKeys("natalia")
    // 5 | sendKeys | css=.form-control | ${KEY_UP}
    await driver.findElement(By.css(".form-control")).sendKeys(Key.UP)
    // 6 | type | css=.form-control | natalia_diaz0612
    await driver.findElement(By.css(".form-control")).sendKeys("natalia_diaz0612")
    // 7 | sendKeys | css=.form-control | ${KEY_ENTER}
    await driver.findElement(By.css(".form-control")).sendKeys(Key.ENTER)
    // 8 | click | css=.d-block | 
    await driver.findElement(By.css(".d-block")).click()
    // 9 | click | css=.d-block | 
    await driver.findElement(By.css(".d-block")).click()
    // 10 | close |  | 
    await driver.close()
  })
})
