// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CP402', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CP402', async function() {
    // Test name: CP402
    // Step # | name | target | value
    // 1 | open | /home.php | 
    await driver.get("https://tucan.toolsincloud.net/home.php")
    // 2 | setWindowSize | 1197x728 | 
    await driver.manage().window().setRect({ width: 1197, height: 728 })
    // 3 | click | css=.form-control | 
    await driver.findElement(By.css(".form-control")).click()
    // 4 | type | css=.form-control | nataliadiaz
    await driver.findElement(By.css(".form-control")).sendKeys("nataliadiaz")
    // 5 | sendKeys | css=.form-control | ${KEY_UP}
    await driver.findElement(By.css(".form-control")).sendKeys(Key.UP)
    // 6 | click | css=.form-control | 
    await driver.findElement(By.css(".form-control")).click()
    // 7 | type | css=.form-control | nataliadiaz_0612
    await driver.findElement(By.css(".form-control")).sendKeys("nataliadiaz_0612")
    // 8 | click | css=.wrapper-right | 
    await driver.findElement(By.css(".wrapper-right")).click()
    // 9 | close |  | 
    await driver.close()
  })
})
